const LOGIN_USER_SUCCESSFUL = "LOGIN_USER_SUCCESSFUL";
const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
const LOGOUT_USER = "LOGOUT_USER";
const REGISTER_USER = "REGISTER_USER";
const REGISTER_WEATHER_QUERY = "REGISTER_WEATHER_QUERY";
const WEATHER_REQUEST = "WEATHER_REQUEST";
const WEATHER_REQUEST_SUCESSFUL = "WEATHER_REQUEST_SUCESSFUL";
const WEATHER_REQUEST_FAILURE = "WEATHER_REQUEST_FAILURE";

export {
  LOGIN_USER_SUCCESSFUL,
  LOGIN_USER_FAILURE,
  LOGOUT_USER,
  REGISTER_USER,
  REGISTER_WEATHER_QUERY,
  WEATHER_REQUEST,
  WEATHER_REQUEST_SUCESSFUL,
  WEATHER_REQUEST_FAILURE
}
